services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["sh", "./scripts/start-dev.sh"]
    env_file:
      - .env
    volumes:
      - .:/app
